Add validate job that checks if dist needs to be rebuilt

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,10 +11,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v1
-    - uses: actions/setup-node@v1
+    - uses: actions/checkout@v3
+    - uses: actions/setup-node@v3
       with:
         node-version: '12.x'
     - run: npm ci
     - run: npm run lint
     - run: npm test
+
+  validate:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '12.x'
+      - name: Validate build
+        shell: bash
+        run: |
+          set -e
+          npm ci
+          git add -A
+          npm run package
+          if [ -n "$(git status --porcelain -- dist)" ]; then
+            echo "::error::Build result differs. Run 'npm run package' then commit and push any changes"
+            git status --porcelain -- dist
+            exit 1
+          fi
